### ISSUE TITLE
msgf+ reports different modification masses then specified

### ISSUE THREAD

**Issue by adder** [sangtaekim/msgfplus#11]
Hi
I  specified the following in my modfication file that I gave to MSGF+.

> NumMods=2
> 15.994915,M,opt,any,Oxidation

However when I check the output mzid file I find PSMs that have 
a modification with massDelta of 15.99492 (as expected) or 15.

Where does this 15 come from?
Did msgf+ also consider a modifciation mass of 15 in its search?

This also happens with other modifciations and different input files.

Thanks in advance

**Comment by alchemistmatt** [comment]
Only thing I can figure is some sort of accidental truncation bug.  The results shouldn't have any unexpected mod masses.  Please compress the .mzid file (.zip or gzip) then e-mail it to proteomics@pnnl.gov  We may also need the instrument data file, but let's just start with the .mzid file for now.

**Comment by adder** [comment]
Hey,
I looked in the raw mzid files myself and they indeed look okay.
I think there is a bug in the parser I am using, so I should have posted this issue somewhere else! :)
Sorry for bothering. I'm closing this.
