### ISSUE TITLE
Phospho TMT protocol

### ISSUE THREAD

**Issue by glormph** [sangtaekim/msgfplus#19]
Hi,
This is maybe more a question than an issue, but I noticed (in 2018.01.30 and earlier) that there are protocols ( `-protocol`) for phospho and for iTRAQ/phospho, but not for TMT/phospho.

Is it fine to just use the TMT protocol (with variable modifications for STY-phospho), should I use the phospho protocol instead, or are both somehow suboptimal? IIRC there was no iTRAQ/phospho protocol in very early MSGF+ versions either.

**Comment by alchemistmatt** [comment]
We use these options with TMT Phospho data:
```-t 20ppm -m 0 -inst 1 -e 1 -ti -1,2 -ntt 2 -tda 1 -minLength 6 -maxLength 50 -minCharge 2 -maxCharge 5 -n 1 -protocol 1 -thread 7 -mod MSGFPlus_Mods.txt -minNumPeaks 5 -addFeatures 1```

With Mods File
```# Max Number of Modifications per peptide
# If this value is large, the search will be slow
NumMods=3

# Static mods
229.1629,*,fix,N-term,TMT6plex
229.1629,K,fix,any,TMT6plex
C2H3N1O1,C,fix,any,Carbamidomethyl     # Fixed Carbamidomethyl C (alkylation)

# Dynamic mods
HO3P,STY,opt,any,Phospho     # Phosphorylation STY
```

I think we may have explored training the software with TMT/phospho data, but found no need for adding a new protocol.  Note that if you do not specify `-protocol 1` the software will assume `-protocol 4` (TMT).  I believe we found via testing that it was better to use the Phospho protocol with Phospho TMT data.

**Comment by glormph** [comment]
Thanks! I'll give that a try!
