### ISSUE TITLE
incorrect retention time in mzid output

### ISSUE THREAD

**Issue by lars20070** [sangtaekim/msgfplus#2]
Consider scan `23302` in this `CC127.mzML` file [1]. The corresponding retention time is 51.05031 minutes.
```
<spectrum index="23301" id="controllerType=0 controllerNumber=1 scan=23302" defaultArrayLength="377">
          <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="2"/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="51.05031" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/>
```
Here the same scan `23302` in the `mzid` result file `CC127.mzid`.  The `scan start time` is reported in seconds, i.e. this number needs to be multiplied by a factor 60.
```
<SpectrumIdentificationResult spectrumID="controllerType=0 controllerNumber=1 scan=23302" spectraData_ref="SID_1" id="SIR_23302">
        <SpectrumIdentificationItem chargeState="3" experimentalMassToCharge="1047.16796875" calculatedMassToCharge="1047.18505859375" peptide_ref="SERVEDDMDSFRYFKELAFAETKNK" rank="1" passThreshold="true" id="SII_23302_1">
          <PeptideEvidenceRef peptideEvidence_ref="PepEv_26508972_VEDDMDSFRYFKELAFAETKNK_86"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002049" name="MS-GF:RawScore" value="27"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002050" name="MS-GF:DeNovoScore" value="306"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002052" name="MS-GF:SpecEValue" value="1.2631749E-6"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002053" name="MS-GF:EValue" value="56.02739"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002054" name="MS-GF:QValue" value="0.9872756"/>
          <cvParam cvRef="PSI-MS" accession="MS:1002055" name="MS-GF:PepQValue" value="0.9687363"/>
          <userParam name="IsotopeError" value="0"/>
          <userParam name="AssumedDissociationMethod" value="HCD"/>
        </SpectrumIdentificationItem>
        <cvParam cvRef="PSI-MS" accession="MS:1001115" name="scan number(s)" value="23302"/>
        <cvParam cvRef="PSI-MS" accession="MS:1000016" name="scan start time" value="51.05031"/>
      </SpectrumIdentificationResult>
```

[1] https://www.dropbox.com/sh/bhz0vm442icogf5/AABkKdDBRM-VliyfQIWL7JDwa

**Comment by FarmGeek4Life** [comment]
All that MS-GF+ fails to do is output the units; the scan start time is not being reported in seconds, your software is reading seconds because it defaults to seconds when the units are not present. A default of seconds is not specified anywhere in the CV or in the mzML or mzIdentML specifications.

**Comment by FarmGeek4Life** [comment]
Anyway, I have a change made that tracks the retention time units and outputs them to the mzid, but I can't build or test because the EBI maven repos are currently offline, apparently due to some datacenter maintenance (happening according to a message on their site).

**Comment by timosachsenberg** [comment]
thanks for the quick response and fix! maybe it's a shortcoming in the specification - will get in contact with the PSI guys

**Comment by lars20070** [comment]
Thanks, Sangtae.

**Comment by FarmGeek4Life** [comment]
Well, as far as I can tell it's not a shortcoming in the specification - the specification for the CV (which cannot be validated using normal XML validation tools) says that the units must be specified:

[Term]
id: MS:1000016
name: scan start time
def: "The time that an analyzer started a scan, relative to the start of the MS run." [PSI:MS]
xref: value-type:xsd\:float "The allowed value-type for this CV term."
is_a: MS:1000503 ! scan attribute
is_a: MS:1002345 ! PSM-level attribute
relationship: has_units UO:0000010 ! second
relationship: has_units UO:0000031 ! minute
 (from https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo)

The lack of outputting the scan start time units was a failure on my part, when I added the output of the scan start time in November 2015 when reading mzML files.

**Comment by FarmGeek4Life** [comment]
[https://github.com/sangtaekim/msgfplus/commit/e2aef7c117b32092686361e1de8651c452beb95b](url)

Adds the scan start time units to the mzid output; building it right now is only possible (in my case) by passing a command line parameter to maven to force it to do an offline build (not checking for dependency package updates), since the EBI maven repos are currently down.

**Comment by FarmGeek4Life** [comment]
EBI Maven repos appear to be back up as of today.

**Comment by lars20070** [comment]
Thanks for [`03de197`](https://github.com/sangtaekim/msgfplus/commit/03de197e30ea7778b955353ae696da2f47ac67f5).
Please let me know once a new [MS-GF+ version](https://omics.pnl.gov/software/ms-gf) is availbale, and I will test it with our adapter.

**Comment by alchemistmatt** [comment]
In case you hadn't noticed, we posted a new version September 16.  I have also posted an even newer version today: https://omics.pnl.gov/software/ms-gf
