### ISSUE TITLE
EtHCD data?

### ISSUE THREAD

**Issue by wyu** [sangtaekim/msgfplus#20]
Hi, is there a plan to add EtHCD support for MSGF+? We're using it for glyco- and HLA peptides. It's be great if we could use MSGF+!

Thanks!
Wen

**Comment by alchemistmatt** [comment]
No, we don't plan to add an explicit scoring model for that.  We evaluated this a year or two back and decided that the ETD scoring model will work just fine for EtHCD spectra.
