### ISSUE TITLE
Parameter for number of missed cleavages?

### ISSUE THREAD

**Issue by hendrikweisser** [sangtaekim/msgfplus#3]
Most search engines have a parameter to specify the number of missed enzyme cleavages that are allowed for peptides. MS-GF+ doesn't seem to have one, at least none is documented [here](https://omics.pnl.gov/software/ms-gf).

What is the default behaviour of MS-GF+ w.r.t. missed cleavages?
Is there already a parameter that just isn't documented?
If no, would it make sense to add such a parameter?

**Comment by alchemistmatt** [comment]
MS-GF+ does not have any limitation on the number of missed cleavages; this is something that you would have to compute and filter on post-search.  The only restrictions on peptides that are applied are minimum and maximum length, and enzyme specificity, plus also the maximum number of dynamic (optional) modifications.
