### ISSUE TITLE
Is it possible to set activationMethod of spec using required activationMethod by default?

### ISSUE THREAD

**Issue by shengqh** [sangtaekim/msgfplus#4]
I am using MGF format for MSGF searching. The ActivationMethod is not required in MGF format. When I perform the MSGFPlus, all spectra will be ignored due to lack of activationMethod. I have to update the code to set required activationMethod as spec activationMethod. I believe that the required activationMethod was passed from command line argument. Is it possible to set activationMethod of spec using required activationMethod by default?

```
            ActivationMethod specActivationMethod = spec.getActivationMethod();
            if (specActivationMethod == null) {
                spec.setActivationMethod(activationMethod);
                specActivationMethod = activationMethod;
```

//                    if (informativeMessageCount < MAX_INFORMATIVE_MESSAGES) {
//                        System.out.println("Skip spectrum " + spec.getID() + " since activationMethod is unknown");
//                        informativeMessageCount++;
//                    } else {
//                        if (informativeMessageCount == MAX_INFORMATIVE_MESSAGES) {
//                            System.out.println(" ...");
//                            informativeMessageCount++;
//                        }
//                    }
//                    continue;
                }

**Comment by FarmGeek4Life** [comment]
Use the following parameter:
[-m FragmentMethodID] (0: As written in the spectrum or CID if no info (Default), 1: CID, 2: ETD, 3: HCD)

**Comment by shengqh** [comment]
I already used -m 3

**Comment by sangtaekim** [comment]
It doesn't ignore spectra if the activation method is not specified. It just assumes the activation method provided by "-m".

**Comment by shengqh** [comment]
The original code has been commented by me. I replaced them with following two lines to let MSGFPlus work on MGF format.

spec.setActivationMethod(activationMethod);
specActivationMethod = activationMethod;

**Comment by sangtaekim** [comment]
I often processed mgf files without any problem. What does the header of your spectrum look like?

**Comment by shengqh** [comment]
###MSMS: 3
BEGIN IONS
TITLE=10sep2013_yeast_control_1.3.3.3.dta
PEPMASS=337.86096
CHARGE=3+
SCANS=3
129.22437 63.3083
130.12553 94.3622
138.12924 33.1769
143.17776 54.302

**Comment by sangtaekim** [comment]
It should work without changing the code. Did it happen in old releases (2015 or earlier)?

**Comment by sangtaekim** [comment]
What was the command line that you used?

**Comment by shengqh** [comment]
I am using the newest version v2016.10.10. Here is my command line.

java -Xmx40G -jar MSGFPlus.jar -s 10sep2013_yeast_control_1.mgf -d uniprot_yeast_201609.REVERSED.fasta -mod msgf_mod.txt -thread 8 -o 10sep2013_yeast_control_1.msgf.mzid -t 10ppm -ti "0,1" -tda 0 -m 3 -inst 0 -e 1 -protocol 5 -ntt 2 -n 2 -addFeatures 1

After replace the SpecKey.class with my updated SpecKey.class, MSGFPlus works well.

**Comment by sangtaekim** [comment]
There must be a bug due to recent changes. Bryson, can you fix it? It will affect lots of people.

**Comment by alchemistmatt** [comment]
Thank you for contacting us.  Yes, this appears to be a recently introduced bug.  We will look into a proper fix.

**Comment by shengqh** [comment]
Thanks a lot.

**Comment by FarmGeek4Life** [comment]
With the latest commit https://github.com/sangtaekim/msgfplus/commit/be713a996fcba514161b1eb9f8d62cf0a522df46 this error should be resolved. However, I don't have the time to test it right now.
Please let us know if it works or not.

**Comment by alchemistmatt** [comment]
I have tested the new version, pushed changes here, and updated https://omics.pnl.gov/software/ms-gf

**Comment by sangtaekim** [comment]
Thanks!
