### ISSUE TITLE
mzid only partially valid for retention time reporting cv term entries

### ISSUE THREAD

**Issue by mwalzer** [sangtaekim/msgfplus#7]
The mzid written after fix for https://github.com/sangtaekim/msgfplus/issues/2 are missing the ```unitCvRef``` attribute in ```cvTerm``` elements with units.

Though all unit attributes in cvTerm elements are optional in the mzid schema, the [spec. doc.](https://github.com/HUPO-PSI/mzIdentML/blob/master/specification_document/specdoc1_1/mzIdentML1.1.0.doc) additionally specifies that if one is present, all must be:
>If a unit term is referenced, this attribute MUST refer to the CV 'id' attribute defined in the cvList in this file.

**Comment by mwalzer** [comment]
I guess a quick fix for existing files is (if *nix tools available) something like:
```
#sed -i "s/unitCvRef=\"minute\"/unitCvRef=\"minute\" unitCvRef=\"UO\"/g" *.mzid
```

**Comment by FarmGeek4Life** [comment]
That was an oversight, thank you for pointing it out to us. Fixed with commit https://github.com/sangtaekim/msgfplus/commit/5acc3a644902edd531ee18c30626cc886b15ad5a
