### ISSUE TITLE
MS-GF:SpecEValue deterministic?

### ISSUE THREAD

**Issue by adder** [sangtaekim/msgfplus#8]
Hi
I was using the MS-GF:SpecEValue score for downstream processing. But I saw that the value of this score for a certain spectrum peptide sequence pair can change depending on the rest of the database.

Is this normal behaviour?

Which of the other scores in the MSGF output should be deterministic? (score is only dependent on spectrum and peptidesequence)

Best regards

**Comment by sangtaekim** [comment]
Yes, it is normal. MS-GF+ derives the frequencies of amino acids (e.g. A: 4%, C: 4.6%, ...) from the database and uses it when computing SpecEValue. 

MSGFScore is not dependent on the database, but its capability to distinguish true and false PSMs is not as good.
